try to replace all occurrances of logprint but now i have this error:
arm-linux-gnueabihf-g++ -c -o vis_00_base.o vis_00_base.cpp -fomit-frame-pointer -fno-common -fno-builtin -mfloat-abi=hard -mcpu=cortex-a9 -march=armv7-a -mtune=cortex-a9 -mthumb-interwork -mtune=cortex-a9 -O3 -ffast-math -funsafe-math-optimizations -mfpu=neon-vfpv3 -std=gnu++17 -Wall -Wextra -Werror -Wfatal-errors -ffunction-sections -fdata-sections -Wno-error=unused-variable -Wno-error=unused-parameter -Wno-error=double-promotion -Wno-error=unused-parameter -Wno-error=shift-negative-value -Wno-error=attributes -Wno-error=sign-compare -pipe --sysroot=/home/martin/pluto-0.35.sysroot/ -I. -D_GNU_SOURCE -D_DEFAULT_SOURCE
In file included from /home/martin/src/fmt/include/fmt/format.h:49,
                 from vis_00_base.cpp:11:
/home/martin/src/fmt/include/fmt/core.h: In instantiation of ‘constexpr fmt::v9::detail::value<Context> fmt::v9::detail::make_value(T&&) [with Context = fmt::v9::basic_format_context<fmt::v9::appender, char>; T = iio_context*&]’:
/home/martin/src/fmt/include/fmt/core.h:1791:29:   required from ‘constexpr fmt::v9::detail::value<Context> fmt::v9::detail::make_arg(T&&) [with bool IS_PACKED = true; Context = fmt::v9::basic_format_context<fmt::v9::appender, char>; fmt::v9::detail::type <anonymous> = (fmt::v9::detail::type)15; T = iio_context*&; typename std::enable_if<IS_PACKED, int>::type <anonymous> = 0]’
/home/martin/src/fmt/include/fmt/core.h:1915:77:   required from ‘constexpr fmt::v9::format_arg_store<Context, Args>::format_arg_store(T&& ...) [with T = {iio_context*&}; Context = fmt::v9::basic_format_context<fmt::v9::appender, char>; Args = {iio_context*}]’
/home/martin/src/fmt/include/fmt/core.h:3222:17:   required from ‘std::__cxx11::string fmt::v9::format(fmt::v9::format_string<T ...>, T&& ...) [with T = {iio_context*&}; std::__cxx11::string = std::__cxx11::basic_string<char>; fmt::v9::format_string<T ...> = fmt::v9::basic_format_string<char, iio_context*&>]’
vis_00_base.cpp:111:62:   required from here
/home/martin/src/fmt/include/fmt/core.h:3222:44:   in ‘constexpr’ expansion of ‘fmt::v9::make_format_args<>((* & args#0))’
/home/martin/src/fmt/include/fmt/core.h:1765:17: error: static assertion failed: Formatting of non-void pointers is disallowed.
   static_assert(formattable_pointer,
                 ^~~~~~~~~~~~~~~~~~~
compilation terminated due to -Wfatal-errors.