logging code is missing
iio_device_impl.cc:(.text._ZNK7libmems13IioDeviceImpl5GetIdEv+0x74): undefined reference to `logging::CheckError::Check(char const*, int, char const*)'

i don't want that anyway